-- MySQL Script generated by MySQL Workbench
-- Tue Dec 22 00:37:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema itransition
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema itransition
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `itransition` DEFAULT CHARACTER SET utf8 ;
USE `itransition` ;

-- -----------------------------------------------------
-- Table `itransition`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itransition`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(100) NULL,
  `address` VARCHAR(100) NULL,
  `phone` VARCHAR(45) NULL,
  `region_support` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `itransition`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `itransition`;
INSERT INTO `itransition`.`User` (`id`, `full_name`, `address`, `phone`, `region_support`) VALUES (1, 'Иван Иванов Иванович', 'Minsk, Victory 10', '+375291111111', 1);
INSERT INTO `itransition`.`User` (`id`, `full_name`, `address`, `phone`, `region_support`) VALUES (2, 'Пётр Петров Петрович', 'Minsk, Victory 22', '+375292222222', 1);
INSERT INTO `itransition`.`User` (`id`, `full_name`, `address`, `phone`, `region_support`) VALUES (3, 'Михаил Круг Александрович', 'Moscow, Red Place 3', '+375773333333', 2);
INSERT INTO `itransition`.`User` (`id`, `full_name`, `address`, `phone`, `region_support`) VALUES (4, 'Владимир Путин Владимирович', 'Moscow, Red Place 1', '+375770000000', 2);
INSERT INTO `itransition`.`User` (`id`, `full_name`, `address`, `phone`, `region_support`) VALUES (5, 'Дмитрий Медведев Анатольевич', 'Moscow, Red Place 2', '+375776000002', 2);
INSERT INTO `itransition`.`User` (`id`, `full_name`, `address`, `phone`, `region_support`) VALUES (6, 'Николай Басков Николаевич', 'Moscow, War 4', '+375775677789', 2);
INSERT INTO `itransition`.`User` (`id`, `full_name`, `address`, `phone`, `region_support`) VALUES (7, 'Борак Обама Махмудович', 'USA, Wall street', '+456330010007', 0);
INSERT INTO `itransition`.`User` (`id`, `full_name`, `address`, `phone`, `region_support`) VALUES (8, 'Пётр Первый Великий', 'St.Petersburg, Coin', '+100347673711', 2);
INSERT INTO `itransition`.`User` (`id`, `full_name`, `address`, `phone`, `region_support`) VALUES (9, 'Ким Чин Ин', 'North Korea, Pyongyang', '+000166678172', 0);
INSERT INTO `itransition`.`User` (`id`, `full_name`, `address`, `phone`, `region_support`) VALUES (10, 'Юлия Темошенко Викторовна', 'Ukraine, Freedom street', '+367998022344', 0);

COMMIT;

